blank_issues_enabled: false
contact_links:
  - name: Knutwurst Wiki
    url: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki
    about: Lots of documentation on installing and using Knutwurst Firmware.
  - name: FAQ
    url: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)
    about: Please look for your question here
  - name: Official Facebook Group (german)
    url: https://www.facebook.com/groups/3094090037303577
    about: If you need general help (english/german), please ask your question here
  - name: Knuwturst Videos on YouTube
    url: https://www.youtube.com/results?search_query=knutwurst+firmware
    about: Tutorials and more from Knutwurst users all around the world. Great for new users!
